"""Regenerate the episode tables inside README.md and README.ms.md from frontmatter.

The tables are written between marker comments rather than pasted in, because a
hand-copied 67-row table goes stale the first time an episode changes and nothing would
catch it. Moving the markers moves the section; deleting them makes the next run append
it at the end.

THE ROW LINKS MUST STAY /blob/ LINKS. That is the whole reason a table exists at all:
GitHub's robots.txt blocks `/*/tree/` and `/*/raw/` but not `/*/blob/`, so a folder
listing is not crawlable while these links are. This used to live in a separate
EPISODES.md, removed once the READMEs carried the same table -- keeping both meant two
places to drift.

Guests come from the `guests` frontmatter, which `scripts/rebuild_roster.py` derives from
the `raw.md` speaker labels (it used to be a `data/_roster.py` scratch file, promoted in
191b8cc). Co-hosts and the producer are never listed here -- that field holds guests only.

Series order is Yang Berhenti Menteri first and Yang Bakar Menteri below it, newest first
within each: the current show before the 2024 one it was renamed from. Owner's call.

  python scripts/build_episode_index.py
"""
import glob
import re
from pathlib import Path

NL = chr(10)
ROOT = Path(__file__).resolve().parent.parent
SERIES = [
    ("yang-berhenti-menteri", "Yang Berhenti Menteri",
     "{n} episodes, 2025 rename onward.", "{n} episod, dari penamaan semula 2025."),
    ("yang-bakar-menteri", "Yang Bakar Menteri",
     "{n} episodes, 2024 run.", "{n} episod, siaran 2024."),
]
BEGIN = "<!-- BEGIN EPISODE LIST -- generated by scripts/build_episode_index.py -->"
END = "<!-- END EPISODE LIST -->"
# per-README: section heading, lead paragraph, table header row
README_TEXT = {
    "README.md": (
        "## All episodes",
        "Newest first, with direct links to all four transcript files. `raw` is the "
        "close-to-verbatim transcript, `mixed` keeps the original code-switched English and "
        "Bahasa Melayu, and `EN` / `MS` are the full translations. The Guests column lists "
        "guests only, never the cast.",
        "| Ep | Date | Title | Length | Hosts | Guests | Transcripts |",
    ),
    "README.ms.md": (
        "## Semua episod",
        "Terbaharu dahulu, dengan pautan terus ke kesemua empat fail transkrip. `raw` ialah "
        "transkrip hampir kata-demi-kata, `mixed` mengekalkan campuran Bahasa Inggeris dan "
        "Bahasa Melayu yang asal, dan `EN` / `MS` ialah terjemahan penuh. Kolum Tetamu "
        "menyenaraikan tetamu sahaja, bukan pengacara.",
        "| Ep | Tarikh | Tajuk | Tempoh | Pengacara | Tetamu | Transkrip |",
    ),
}
FIELD_RE = {k: re.compile(rf"^{k}:\s*(.*)$", re.M)
            for k in ("title", "youtube_url", "publish_date", "duration")}
LIST_RE = {key: re.compile(rf"^{key}:\s*(\[\]|\n(?:- .*\n)*)", re.M)
           for key in ("hosts", "guests")}


def cell(text):
    """Escape what would otherwise break out of a markdown table cell."""
    return text.replace("|", "\\|").replace("\n", " ").strip()


def read_fields(path):
    text = path.read_text(encoding="utf-8")
    frontmatter = text.split("---", 2)[1]
    out = {}
    for key, pattern in FIELD_RE.items():
        m = pattern.search(frontmatter)
        out[key] = (m.group(1).strip().strip("'\"") if m else "")
    for key, pattern in LIST_RE.items():
        m = pattern.search(frontmatter)
        out[key] = re.findall(r"- (.+)", m.group(1)) if m else []
    return out


def episode_rows(series_dir):
    rows = []
    for d in glob.glob(str(ROOT / "episodes" / series_dir / "*")):
        d = Path(d)
        interview = d / "interview.md"
        raw = d / "raw.md"
        if not raw.exists():
            continue
        # interview.md carries hosts/guests; fall back to raw.md for the rest
        fields = read_fields(interview if interview.exists() else raw)
        if not fields["title"]:
            fields.update({k: v for k, v in read_fields(raw).items() if v})
        number = re.search(r"-ep(\d+)-", d.name).group(1)
        rel = f"episodes/{series_dir}/{d.name}"
        links = " · ".join(
            f"[{label}]({rel}/{name})" for label, name in
            (("raw", "raw.md"), ("mixed", "interview.md"),
             ("EN", "interview-en.md"), ("MS", "interview-ms.md"))
            if (d / name).exists())
        rows.append((
            fields["publish_date"], number,
            f"| {number} | {fields['publish_date']} | "
            f"[{cell(fields['title'])}]({fields['youtube_url']}) | "
            f"{fields['duration']} | {cell(', '.join(fields['hosts']))} | "
            f"{cell(', '.join(fields['guests']))} | {links} |"))
    rows.sort(reverse=True)  # newest first
    return [r[2] for r in rows]


def inject_into_readme(filename):
    """Rewrite the episode tables inside a README, between BEGIN/END markers."""
    heading, blurb, columns = README_TEXT[filename]
    malay = filename.endswith('.ms.md')
    blocks, total = [], 0
    for series_dir, series_heading, blurb_en, blurb_ms in SERIES:
        rows = episode_rows(series_dir)
        if not rows:
            continue
        total += len(rows)
        note = (blurb_ms if malay else blurb_en).format(n=len(rows))
        blocks.append(
            "### " + series_heading + NL * 2 + note + NL * 2
            + columns + NL + "|---|---|---|---|---|---|---|" + NL
            + NL.join(rows))
    section = (BEGIN + NL * 2 + heading + NL * 2 + blurb + NL * 2
               + (NL * 2).join(blocks) + NL * 2 + END)
    path = ROOT / filename
    text = path.read_text(encoding="utf-8")
    if BEGIN in text and END in text:
        head, rest = text.split(BEGIN, 1)
        text = head + section + rest.split(END, 1)[1]
    else:
        text = text.rstrip(NL) + NL * 2 + section + NL
    path.write_text(text, encoding="utf-8")
    return total


def main():
    for name in README_TEXT:
        print(f"wrote {name}: {inject_into_readme(name)} episodes inlined")


if __name__ == "__main__":
    main()
