"""Generate TOPICS.md: every episode and the subjects it covers, on one page.

WHY THIS EXISTS. The `topics:` frontmatter is the only part of this archive where
anything read an episode and said what it is about, and it was invisible -- sitting in 68
separate files, while README.md (the file a search engine actually reads) listed episodes
only by number, date and title. 716 topic lines that nobody could find. This puts them on
one crawlable page, oldest first, so a subject can be followed across the run.

WHY THERE IS NO CROSS-EPISODE TOPIC TABLE HERE, though there was for one commit. It was
built by pattern-matching the transcripts and ranking by frequency, and it missed the main
theme of episode after episode. Each miss had its own cause, which is the point -- the
approach needed a new patch per subject:

  Rohingya    71 uses in ep53, in its title. The phrase pattern required TWO capitalised
              words, so every single-word proper noun was invisible.
  e-Fishery   37 uses in ep56, in its title, spelled four ways. Lowercase-initial and
              hyphenated, so it matched no pattern at all.
  AUKU        49 uses in ep60, in its title. Present in only two episodes, so an
              episode-spread threshold of five dropped it.
  KWAP        6 uses. Below every threshold, and central to the episode.
  Gen Z       ep52's actual theme. The statistics offered `Zaim Zulkifli` instead -- a
              guest, already listed in the Guests column, and not what the episode is about.

Every one of those was already written down in the frontmatter: "Krisis pelarian Rohingya
di Malaysia", "e-Fishery fraud and startup/VC funding explainer", "Pemansuhan AUKU dan
reformasi pendidikan tinggi", "KWAP investment in e-Fishery and due diligence failures",
"Gen Z identity, social media culture, and generational differences". The statistics were
a detour around data that was already correct. So this page prints that data verbatim and
computes nothing.

  python scripts/build_topic_index.py      # writes TOPICS.md, updates both READMEs
"""
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "TOPICS.md"
NL = chr(10)

TEASER_BEGIN = "<!-- BEGIN TOPIC TEASER -- generated by scripts/build_topic_index.py -->"
TEASER_END = "<!-- END TOPIC TEASER -->"
TEASER_TEXT = {
    "README.md": (
        "## What each episode covers",
        "**[TOPICS.md](TOPICS.md) lists every episode and its subjects on one page**, "
        "oldest first, so you can follow an issue across the run rather than guessing "
        "which episode to open. An issue here usually spans several episodes and a "
        "position can change across them, so reading one can mislead you about the "
        "argument as a whole.",
        "It is a record of what was said and when, not a fact-check. It does not "
        "establish whether a claim is correct or who said something first -- those need "
        "sources beyond one podcast.",
    ),
    "README.ms.md": (
        "## Apa yang dibincangkan setiap episod",
        "**[TOPICS.md](TOPICS.md) menyenaraikan setiap episod dan subjeknya dalam satu "
        "halaman**, terlama dahulu, supaya anda boleh mengikuti satu isu merentas "
        "keseluruhan siaran dan bukan meneka episod mana untuk dibuka. Satu isu di sini "
        "biasanya merangkumi beberapa episod dan pendirian boleh berubah antaranya, jadi "
        "membaca satu episod sahaja boleh mengelirukan anda tentang hujah keseluruhannya.",
        "Ia ialah rekod apa yang diucapkan dan bila, bukan semakan fakta. Ia tidak "
        "menentukan sama ada sesuatu dakwaan itu benar atau siapa yang menyebutnya "
        "dahulu -- itu memerlukan sumber di luar satu podcast.",
    ),
}


# A chapter line in a YouTube description: "16:01  Anwar Sekarang Bukan Yang Dulu".
CHAPTER = re.compile(r"^[^\w\n]{0,4}((?:\d{1,2}:)?\d{1,2}:\d{2})\s+(\S.{2,90})$", re.M)


def segments_by_video():
    """{video_id: [(seconds, label)]} from the show's OWN chapter markers.

    THE SHOW ALREADY SAID WHAT EACH SEGMENT IS. 39 of the 68 descriptions carry chapter
    markers written by the people who made the episode, timestamped, and they were sitting
    unused in data/manifest.json while the `topics:` list for some episodes had a single
    line for three hours of talk -- ep35 has one topic and nine chapters, among them
    "Bloomberg Kasi Kantoi Azam Baki" and "Isu Rumah Ibadat", which are exactly what its
    title promises and its topic list omits.

    Read at build time rather than copied into the episode frontmatter: no episode file
    changes, so nothing here can disturb the transcripts or the QA suite.
    """
    manifest = json.loads((ROOT / "data" / "manifest.json").read_text(encoding="utf-8"))
    out = {}
    for ep in manifest:
        chapters = []
        for stamp, label in CHAPTER.findall(ep.get("description") or ""):
            parts = [int(p) for p in stamp.split(":")]
            while len(parts) < 3:
                parts.insert(0, 0)
            secs = parts[0] * 3600 + parts[1] * 60 + parts[2]
            label = label.strip().rstrip("-–—").strip()
            if label:
                chapters.append((secs, label))
        # Three is where a run of timestamps is a chapter list rather than a stray time
        # mentioned in prose, and the labels must climb: a real list is in order.
        if len(chapters) >= 3 and all(b[0] > a[0] for a, b in zip(chapters, chapters[1:])):
            out[ep["video_id"]] = chapters
    return out


def episodes():
    """[(date, tag, title, video_id, dir, topics)] oldest first."""
    out = []
    for d in sorted((ROOT / "episodes").glob("*/*")):
        pub = d / "interview.md"
        if not pub.exists():
            continue
        text = pub.read_text(encoding="utf-8")

        def field(name):
            m = re.search(rf"^{name}:\s*'?(.*?)'?$", text, re.M)
            return m.group(1).strip() if m else ""

        block = re.search(r"^topics:\n((?:- .*\n)+)", text, re.M)
        topics = [t[2:].strip().strip("'\"") for t in block.group(1).splitlines()] \
            if block else []
        num = re.search(r"-(ep\d+)-", d.name)
        show = "YBhM" if "berhenti" in str(d) else "YBkM"
        out.append((field("publish_date"), f"{show} {num.group(1) if num else '?'}",
                    field("title"), field("video_id"), d, topics))
    return sorted(out)


def write_topics(eps):
    parts = ["""# What each episode covers

Every episode in the archive, oldest first, with the subjects it covers. Generated by
`scripts/build_topic_index.py` from each episode's own frontmatter, so it stays in step
with the transcripts.

An issue here usually spans several episodes, and a position can change across them.
Reading one episode can mislead you about the argument as a whole, which is the reason
this page is ordered by date rather than grouped.

**This is a record of what was said and when, not a fact-check.** It does not establish
whether a claim is correct, or who said something first -- those need sources beyond one
podcast. What it gives you is the primary material, in order, and a transcript you can
search.

Every transcript is machine-generated and carries the accuracy caveats in
[README.md](README.md#accuracy-note). Check the video before quoting anyone.
"""]
    for date, tag, title, vid, d, topics in eps:
        rel = f"episodes/{d.parent.name}/{d.name}"
        parts.append(f"{NL}## {tag} &mdash; {date}{NL}")
        parts.append(f"[{title}](https://www.youtube.com/watch?v={vid}) &middot; "
                     f"[raw]({rel}/raw.md) &middot; [mixed]({rel}/interview.md) &middot; "
                     f"[EN]({rel}/interview-en.md) &middot; [MS]({rel}/interview-ms.md)"
                     f"{NL}")
        parts += [f"- {t}" for t in topics] or ["- _no topics recorded_"]
    OUT.write_text(NL.join(parts) + NL, encoding="utf-8")


def inject_teaser(filename):
    heading, intro, caveat = TEASER_TEXT[filename]
    section = (NL * 2).join([TEASER_BEGIN, heading, intro, caveat, TEASER_END])
    path = ROOT / filename
    text = path.read_text(encoding="utf-8")
    if TEASER_BEGIN in text and TEASER_END in text:
        head, rest = text.split(TEASER_BEGIN, 1)
        text = head + section + rest.split(TEASER_END, 1)[1]
    else:
        # Above the episode tables, so a crawler meets subject words before 68 rows.
        text = text.replace("<!-- BEGIN EPISODE LIST",
                            section + NL * 2 + "<!-- BEGIN EPISODE LIST", 1)
    path.write_text(text, encoding="utf-8")


def main():
    eps = episodes()
    write_topics(eps)
    for readme in TEASER_TEXT:
        inject_teaser(readme)
    print(f"wrote {OUT.name}: {len(eps)} episodes, "
          f"{sum(len(e[5]) for e in eps)} topic lines")
    print("updated the topic pointer in README.md and README.ms.md")


if __name__ == "__main__":
    main()
