"""Catch a tracked document whose numbers no longer match the corpus.

WHY THIS EXISTS. The session-closing checklist has asked every session to "update stale
documents" since 2026-09-14, and CLAUDE.md's own governing principle says why that was
never enough: *a rule with no mechanism gets skipped*. It was skipped. On 2026-09-16
TOPICS.md was 320 insertions and 282 deletions out of step with its own generator, and
README.md called the same folder 64 episodes in two places and 61 in a third.

Two classes, because they fail differently:

  1. A GENERATED document drifts when nobody re-runs its generator. Nothing warns you --
     the file looks fine, it is just describing an older corpus. So this re-runs each
     generator and diffs its output against the committed file.
  2. A PER-RUN EPISODE COUNT drifts when the corpus grows. It is checked only where the
     document names the run's FOLDER, plus the recorded hours.

WHAT IS DELIBERATELY NOT CHECKED, and why the scope is this narrow. A first version read
every `N episodes` in the public documents and reported five findings. Four were correct
prose it had misread:

  - `README.md:3` names both shows in one sentence, then gives the corpus total. Nothing in
    the line marks which number belongs to which scope.
  - `METHODOLOGY.md:185` says "39 of 70 episodes carry at least one flag, ... and 0
    episodes are unprocessed". Two counts, neither a corpus total.
  - `METHODOLOGY.md:187` says "40 episodes now hold a re-cut raw.md". A real subset.

So a bare count in prose is not mechanically verifiable, and this does not try. What IS
unambiguous is a count sitting next to the run's folder path: `[Yang Berhenti Menteri, 64
episodes](episodes/yang-berhenti-menteri/)` and `yang-berhenti-menteri/ # ... 64 episodes`.
Both of today's real defects had that shape. Numbers in ARCHITECTURE.md and
ENGINEERING_LOG.md are skipped entirely: they are dated measurement records ("21 tails
moved across 17 episodes"), and the checklist's own instruction is to date a historical
statement rather than restate it. A checker whose output is mostly correct lines gets
ignored, which is the failure this script exists to fix.

  python scripts/check_stale_docs.py            # report only, restores what it regenerated
  python scripts/check_stale_docs.py --write     # keep the regenerated documents
"""
import argparse
import difflib
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PY = sys.executable

# A generated document, the command that writes it, and every OTHER file that command
# touches (build_topic_index.py also rewrites the topic pointer in both READMEs, so those
# have to be snapshotted too or a report-only run leaves them changed).
GENERATED = [
    ("TOPICS.md", ["scripts/build_topic_index.py"], ["README.md", "README.ms.md"]),
    ("QA_CHECKLIST.md", ["scripts/qa_check.py"], []),
]
# NOT listed: data/rule7_contested_boundaries.md. Its own header says "Generated by
# `check_overlap_boundaries.py --all`", and that script only PRINTS -- it writes no file.
# So the document was transcribed from the output by hand, and a checker cannot judge it
# by regenerating. It is already marked CLOSED with its date, so it reads as the record it
# is. Noted here so the next session does not go looking for the writer.

DOCS = ("README.md", "README.ms.md", "METHODOLOGY.md")
COUNT = re.compile(r"\b(\d{1,3})\s+(?:episodes|episod)\b")
HOURS = re.compile(r"\b(\d{2,4})\s+(?:hours|jam)\b")
LINK = re.compile(r"\[([^\]]*)\]\(([^)]*)\)")


def measured():
    runs = {d.name: sum(1 for p in d.iterdir() if p.is_dir())
            for d in (ROOT / "episodes").iterdir() if d.is_dir()}
    manifest = json.loads((ROOT / "data" / "manifest.json").read_text(encoding="utf-8"))
    hours = sum(e.get("duration_seconds") or 0 for e in manifest) / 3600
    return runs, sum(runs.values()), hours


def scoped_counts(line, runs):
    """Yield (folder, claimed count) for every count this line scopes to ONE run folder.

    Two shapes, both unambiguous:

      1. A markdown link whose TARGET is the folder and whose TEXT holds the count. README
         writes the browse-by-run line that way, and it carried 64 for a 64-episode folder
         while the tree below it said 61.
      2. A line that names exactly one folder path and holds no link, such as the
         folder-tree comment `yang-berhenti-menteri/   # 2025 rename onward, 64 episodes`.
    """
    for text, target in LINK.findall(line):
        for folder in runs:
            if folder + "/" in target:
                for claim in COUNT.findall(text):
                    yield folder, claim
    rest = LINK.sub(" ", line)
    named = [f for f in runs if f + "/" in rest]
    if len(named) == 1:
        for claim in COUNT.findall(rest):
            yield named[0], claim


def check_counts(runs, hours):
    bad = []
    for name in DOCS:
        path = ROOT / name
        if not path.exists():
            continue
        for n, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            for folder, claim in scoped_counts(line, runs):
                if int(claim) != runs[folder]:
                    bad.append(f"{name}:{n}: says {claim} episodes for {folder}, "
                               f"the folder holds {runs[folder]}")
            for claim in HOURS.findall(line):
                if abs(int(claim) - hours) > 1:
                    bad.append(f"{name}:{n}: says {claim} hours, measured {hours:.1f}")
    return bad


def check_generated(write):
    bad = []
    for target, cmd, also in GENERATED:
        path = ROOT / target
        if not path.exists():
            bad.append(f"{target}: generated document is missing")
            continue
        touched = [path] + [ROOT / a for a in also]
        before = {p: p.read_bytes() for p in touched if p.exists()}
        r = subprocess.run([PY] + cmd, cwd=ROOT, capture_output=True, text=True,
                           encoding="utf-8", errors="replace")
        if r.returncode:
            bad.append(f"{target}: its generator failed, so staleness cannot be judged "
                       f"({' '.join(cmd)}) -- {(r.stderr or r.stdout).strip()[-200:]}")
        now = path.read_bytes() if path.exists() else b""
        if now != before.get(path, b""):
            old = before.get(path, b"").decode("utf-8", "replace").splitlines()
            new = now.decode("utf-8", "replace").splitlines()
            diff = list(difflib.unified_diff(old, new, n=0))
            adds = sum(1 for l in diff if l.startswith("+") and not l.startswith("+++"))
            dels = sum(1 for l in diff if l.startswith("-") and not l.startswith("---"))
            bad.append(f"{target}: STALE -- regenerating it changes the file "
                       f"(+{adds}/-{dels} lines). Its generator is `{' '.join(cmd)}`.")
        if not write:
            for p, blob in before.items():
                if p.read_bytes() != blob:
                    p.write_bytes(blob)
    return bad


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true",
                    help="keep the regenerated documents instead of restoring them")
    ap.add_argument("--counts-only", action="store_true",
                    help="skip the generators, which take minutes (qa_check.py reads all "
                         "70 episodes)")
    a = ap.parse_args()
    runs, episodes, hours = measured()
    print(f"measured: {episodes} episodes, {hours:.1f} hours, "
          + ", ".join(f"{k} {v}" for k, v in sorted(runs.items())))
    findings = ([] if a.counts_only else check_generated(a.write)) \
        + check_counts(runs, hours)
    for f in findings:
        print("  " + f)
    print(f"{len(findings)} stale-document finding(s)"
          + ("" if a.write else " -- report only, nothing kept"))
    sys.exit(1 if findings and not a.write else 0)


if __name__ == "__main__":
    main()
