"""Audit all episodes for known pipeline failure signatures and write a checklist.

Checks per episode:
  - raw.md exists and has sane [MM:SS] timestamp coverage vs duration_seconds
    (catches incomplete transcription and hallucinated runaway timestamps)
  - raw.md has real paragraph breaks between turns, not one wall-of-text block
    (catches the missing-"\n\n" bug that silently bypasses chunking)
  - interview.md / interview-en.md / interview-ms.md exist and are not
    disproportionately short vs raw.md (catches the resulting truncated rewrite)

Usage:
  python scripts/qa_check.py            # writes QA_CHECKLIST.md
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
EPISODES_DIR = ROOT / "episodes"
OUT_PATH = ROOT / "QA_CHECKLIST.md"

TIMESTAMP_RE = re.compile(r"\[(?:(\d+):)?(\d+):(\d+)\]")
FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)

MIN_COVERAGE_PCT = 95
MAX_COVERAGE_PCT = 150
MAX_BLOCK_CHARS = 20_000  # a single real speaker turn is never this long
MIN_INTERVIEW_RATIO = 0.35  # interview.md chars / raw.md chars, calibrated against known-good episodes (0.74-0.93)


def last_timestamp_seconds(text):
    matches = TIMESTAMP_RE.findall(text)
    if not matches:
        return None
    h, m, s = matches[-1]
    return (int(h) if h else 0) * 3600 + int(m) * 60 + int(s)


def duration_seconds(frontmatter_text):
    m = re.search(r"duration_seconds:\s*(\d+)", frontmatter_text)
    return int(m.group(1)) if m else None


def check_episode(ep_dir):
    issues = []
    raw_path = ep_dir / "raw.md"
    if not raw_path.exists():
        return ["missing raw.md"]

    raw_text = raw_path.read_text(encoding="utf-8")
    fm_match = FRONTMATTER_RE.match(raw_text)
    duration = duration_seconds(fm_match.group(1)) if fm_match else None
    body = raw_text[fm_match.end():] if fm_match else raw_text

    if duration:
        covered = last_timestamp_seconds(body)
        if covered is None:
            issues.append("no timestamps found in raw.md")
        else:
            pct = covered / duration * 100
            if pct < MIN_COVERAGE_PCT:
                issues.append(f"raw.md timestamp coverage only {pct:.0f}% (last ts {covered}s of {duration}s)")
            elif pct > MAX_COVERAGE_PCT:
                issues.append(f"raw.md timestamp coverage {pct:.0f}% -- likely hallucinated runaway timestamps")

    blocks = body.split("\n\n")
    max_block = max((len(b) for b in blocks), default=0)
    if max_block > MAX_BLOCK_CHARS:
        issues.append(f"raw.md has a {max_block}-char block with no paragraph breaks (wall-of-text)")

    raw_len = len(raw_text)
    for name in ("interview.md", "interview-en.md", "interview-ms.md"):
        path = ep_dir / name
        if not path.exists():
            issues.append(f"missing {name}")
            continue
        ratio = len(path.read_text(encoding="utf-8")) / raw_len if raw_len else 0
        if ratio < MIN_INTERVIEW_RATIO:
            issues.append(f"{name} looks truncated (ratio {ratio:.2f} vs raw.md, expected >= {MIN_INTERVIEW_RATIO})")

    return issues


def main():
    results = {}
    for ep_dir in sorted(EPISODES_DIR.iterdir()):
        if not ep_dir.is_dir():
            continue
        results[ep_dir.name] = check_episode(ep_dir)

    total = len(results)
    broken = {slug: issues for slug, issues in results.items() if issues}

    lines = [
        "# QA Checklist",
        "",
        f"Generated by `scripts/qa_check.py`. {total - len(broken)}/{total} episodes clean, {len(broken)} flagged.",
        "",
        "Re-run after any reprocessing batch: `python scripts/qa_check.py`.",
        "",
    ]
    if broken:
        lines.append("## Flagged episodes")
        lines.append("")
        for slug, issues in broken.items():
            lines.append(f"- [ ] **{slug}**")
            for issue in issues:
                lines.append(f"  - {issue}")
        lines.append("")
    lines.append("## Clean episodes")
    lines.append("")
    for slug, issues in results.items():
        if not issues:
            lines.append(f"- [x] {slug}")
    lines.append("")

    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT_PATH} -- {len(broken)}/{total} flagged")


if __name__ == "__main__":
    main()
